language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test:cov
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: build
  keep_history: true
  on:
    branch: master